'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
<<<<<<< HEAD
    
=======
<<<<<<< HEAD
    
=======

>>>>>>> 216d8087a2f689497a661d7a92fca7fbdf6d69e1
>>>>>>> 5161a45d4146e7ea02036b6319d10c22e24ea894
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication
<<<<<<< HEAD
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
=======
<<<<<<< HEAD
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
=======

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
>>>>>>> 216d8087a2f689497a661d7a92fca7fbdf6d69e1
>>>>>>> 5161a45d4146e7ea02036b6319d10c22e24ea894
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
<<<<<<< HEAD
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
=======
<<<<<<< HEAD
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
=======

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
>>>>>>> 216d8087a2f689497a661d7a92fca7fbdf6d69e1
>>>>>>> 5161a45d4146e7ea02036b6319d10c22e24ea894
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.coffeeshopMD.frm_login
        End Sub
    End Class
End Namespace
